### ISSUE TITLE
Fix request

### ISSUE THREAD

**Issue by tech-success** [tonyldo/tonyldo-hassio-addons#10]
Config file is attached. When we start addon, it fails on get gateway list request (HTTPSConnection ). Please fix this...
ttlockclientapp: id
ttlocktoken: token
publishstatedelay: 60
publishbatterydelay: 300
loglevel: ERROR
mqttbrokerhost: 10.0.5.15
mqttbrokerport: '1883'
mqttbrokeruser: Имран
mqttbrokerpass: Qaz12345678_9

This is the log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020-11-18 18:24:50 - [ERROR] TTLOCK2MQTT: Error main method
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd238709d30>: Failed to establish a new connection: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ttlock.com', port=443): Max retries exceeded with url: /v3/gateway/list?clientId=610626a4526744958c54655a4d0f6b33&accessToken=cd69c2d503d5ea4c06015b649f05980e&pageNo=1&pageSize=20&date=1605713085681 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd238709d30>: Failed to establish a new connection: [Errno -3] Try again'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/ttlock_adapter.py", line 318, in main
    createClients(broker, port, broker_user, broker_pass,
  File "/ttlock_adapter.py", line 301, in createClients
    for gateway in ttlock.get_gateway_generator():
  File "/usr/local/lib/python3.9/site-packages/ttlockwrapper/ttlock.py", line 99, in get_gateway_generator
    _response = TTLock.__send_request__(_url_request).json()
  File "/usr/local/lib/python3.9/site-packages/ttlockwrapper/ttlock.py", line 25, in __send_request__
    _response = requests.request(method,_url_request, headers=_headers)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.ttlock.com', port=443): Max retries exceeded with url: /v3/gateway/list?clientId=610626a4526744958c54655a4d0f6b33&accessToken=cd69c2d503d5ea4c06015b649f05980e&pageNo=1&pageSize=20&date=1605713085681 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd238709d30>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by tonyldo** [comment]
Hello, this error sounds like that u have some problem with to access TTLockAPI site. U are behind a proxy or firewall that was blocking host='api.ttlock.com', port=443 ?

**Comment by tech-success** [comment]
Hi. I don't know what the reason is. I've re-configured network on controller using nmcli, and the I've re-connected lock and gateway. And after this problem has gone. Anyway it repeats when I change network parameters. I have to delete lock and gateway and then search and join them again. It looks like a phantom bug. Something crashes in your plugin16:52, 22 декабря 2020 г., ANTONIO CAMPOS <notifications@github.com>:
Hello, this error sounds like that u have some problem with to access TTLockAPI site. U are behind a proxy or firewall that was blocking host='api.ttlock.com', port=443 ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by tonyldo** [comment]
Sorry, i dont undetstand... what kind of change did u do at your network?

**Comment by tech-success** [comment]
Change wifi network. I've moved to another building with my controller. Wifi network is different. I thought that if I change network settings in my controller and in mqtt system will recover but it wasn't. So that's why I decided to write you. The only solution i found was to delete lock, gateway, and reconfigure plugin and MQTT. After that it worked. Please discover17:00, 22 декабря 2020 г., ANTONIO CAMPOS <notifications@github.com>:
Sorry, i dont undetstand... what kind of change did u do at your network?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by tonyldo** [comment]
Sorry but this not make sense... The error that u print in this issue is connection error from your ttlock2mqtt addon (HassIO server) to The Ttlock API at the internet. If there is another error about your local network isn't in these logs.

**Comment by tonyldo** [comment]
i will close this issue ... if something news happened let me know
