### ISSUE TITLE
Failed to start Add On

### ISSUE THREAD

**Issue by leofig-rj** [tonyldo/tonyldo-hassio-addons#15]
I installed TTLock2MQTT version: 0.4, with the configuration:
ttlockclientapp: my client_id
ttlocktoken: my api_token
mqttbrokerhost: 10.0.1.20
mqttbrokerport: '1883'
mqttbrokeruser: my mqqt_usr
mqttbrokerpass: my mqtt_psw
publishbatterydelay: 300
publishstatedelay: 60
loglevel: info
maxthreads: 200

I'm using Raspberry Pi 4.

When I start, I see in log:

s6-overlay-suexec: fatal: can only run as pid 1

I've uninstalled and tried a few times without success.

Please, am I making a mistake?

**Comment by leofig-rj** [comment]
Core-2022.5.4
Home Assistant OS 8.0
Supervisor | true
Docker | true
Python | 3.9.9
Linux | 5.15.32-v8
CPU | aarch64
Supervisor-2022.05.2
Docker | 20.10.14
rpi4-64

**Comment by tonyldo** [comment]
There is a new version in the docker engine used by hass to run the addons. I will need up a new version.

https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

**Comment by lvibe** [comment]
First off thank you both for your efforts on this!

I am running into an issue with version 0.5 when trying to unlock:

2022-05-31 10:54:32 - [ERROR] TTLOCK2MQTT: Client LOCK-5591978-1654005992 error: Error returned from TTlockAPI: Error_code 1 - failed or means no
2022-05-31 10:54:34 - [ERROR] TTLOCK2MQTT: Client 5591978 error on received mqtt message
Traceback (most recent call last):
  File "/usr/bin/ttlock_adapter.py", line 49, in cb_on_message
    client.handleMessage(message)
  File "/usr/bin/ttlock_adapter.py", line 192, in handleMessage
    result = self.ttlock.unlock(self.getLockId())
  File "/usr/local/lib/python3.10/site-packages/ttlockwrapper/ttlock.py", line 198, in unlock
    return TTLock.__is_erro_code_success__(TTLock.__send_request__(_url_request).json().get(ERROR_CODE_FIELD))
  File "/usr/local/lib/python3.10/site-packages/ttlockwrapper/ttlock.py", line 28, in __send_request__
    raise TTlockAPIError(error_code=_response.json().get(ERROR_CODE_FIELD),menssage=_response.json().get(MENSSAGE_FIELD))
ttlockwrapper.ttlock.TTlockAPIError: Error returned from TTlockAPI: Error_code -4043 - The function is not supported for this lock.

**Comment by tonyldo** [comment]
Pull request with the new features mergged
