### ISSUE TITLE
Home Assistant Integration Error

### ISSUE THREAD

**Issue by eng-andycarlos** [tonyldo/tonyldo-hassio-addons#17]
**Hello**

- I created the account at https://open.ttlock.com/login
- I created the application and got the "client_id" and "client_secret" aproved
- Installed the TTLock2MQTT Add-on and configured with the above information.

LOG: 

`File "/usr/bin/ttlock_adapter.py", line 326, in main
    createClients(broker, port, broker_user, broker_pass,
  File "/usr/bin/ttlock_adapter.py", line 306, in createClients
    for gateway in ttlock.get_gateway_generator():
  File "/usr/local/lib/python3.10/site-packages/ttlockwrapper/ttlock.py", line 99, in get_gateway_generator
    _response = TTLock.__send_request__(_url_request).json()
  File "/usr/local/lib/python3.10/site-packages/ttlockwrapper/ttlock.py", line 28, in __send_request__
    raise TTlockAPIError(error_code=_response.json().get(ERROR_CODE_FIELD),menssage=_response.json().get(MENSSAGE_FIELD))
ttlockwrapper.ttlock.TTlockAPIError: Error returned from TTlockAPI: Error_code 10003 - invalid token
2022-06-21 05:41:04 - [DEBUG] TTLOCK2MQTT: Starting new HTTPS connection (1): api.ttlock.com:443
2022-06-21 05:41:06 - [DEBUG] TTLOCK2MQTT: https://api.ttlock.com:443 "GET /v3/gateway/list?clientId=0bb21bf0b9a54a0f913c7dfa471fba93&accessToken=39152cae3c566e0a3611370cae282d60&pageNo=1&pageSize=20&date=1655800864848 HTTP/1.1" 200 None
2022-06-21 05:41:06 - [ERROR] TTLOCK2MQTT: Error main method
Traceback (most recent call last):
  File "/usr/bin/ttlock_adapter.py", line 326, in main
    createClients(broker, port, broker_user, broker_pass,
  File "/usr/bin/ttlock_adapter.py", line 306, in createClients
    for gateway in ttlock.get_gateway_generator():
  File "/usr/local/lib/python3.10/site-packages/ttlockwrapper/ttlock.py", line 99, in get_gateway_generator
    _response = TTLock.__send_request__(_url_request).json()
  File "/usr/local/lib/python3.10/site-packages/ttlockwrapper/ttlock.py", line 28, in __send_request__
    raise TTlockAPIError(error_code=_response.json().get(ERROR_CODE_FIELD),menssage=_response.json().get(MENSSAGE_FIELD))
ttlockwrapper.ttlock.TTlockAPIError: Error returned from TTlockAPI: Error_code 10003 - invalid token
2022-06-21 05:42:06 - [DEBUG] TTLOCK2MQTT: Starting new HTTPS connection (1): api.ttlock.com:443
2022-06-21 05:42:07 - [DEBUG] TTLOCK2MQTT: https://api.ttlock.com:443 "GET /v3/gateway/list?clientId=0bb21bf0b9a54a0f913c7dfa471fba93&accessToken=39152cae3c566e0a3611370cae282d60&pageNo=1&pageSize=20&date=1655800926197 HTTP/1.1" 200 None
2022-06-21 05:42:07 - [ERROR] TTLOCK2MQTT: Error main method`

**In the instructions, I didn't understand where I should perform this action:**

Create a user for this application and get the access token:
$ pip install ttlockio
$ create_user_and_access_token YOUR_APP_CLIENT_ID YOUR_APP_CLIENTSECRET NEW_NAME_FOR_YOUR_USER NEW_PASS_FOR_YOUR_USER https://yoursitedomain.com/
ATTENTION: you need pass the NEW_PASS_FOR_YOUR_USER with max 32 chars, low case

Return:

[
  {
    "ttlockclientapp": "YOUR_APP_CLIENT_ID",
    "ttlocktoken": "YOUR_ACCESS_TOKEN",
    "username": "YOUR_APP_NAME_CONCAT_NEW_NAME_FOR_YOUR_USER",
    "refreshtoken": "YOUR_REFRESH_TOKEN"
  }
]

Tks

**Comment by tonyldo** [comment]
You didnt get a valid oauth token. These steps above are the use of a script present in ttlockio python lib. It help you to get the oauth token. See this: https://github.com/tonyldo/ttlockio

**Comment by eng-andycarlos** [comment]
Antonio, obrigado por responder 🙏

I installed TTLock2MQTT on home assistant.

The command
`pip install ttlockio`
should I run in Home Assistant terminal?

In the second command I didn't understand what the URL at the end is **(https://yoursitedomain.com/)**


`create_user_and_access_token YOUR_APP_CLIENT_ID YOUR_APP_CLIENTSECRET NEW_NAME_FOR_YOUR_USER NEW_PASS_FOR_YOUR_USER https://yoursitedomain.com/`

Tks

**Comment by tonyldo** [comment]
Hi, sorry for respond so lately...
There is new tutorial at https://github.com/tonyldo/ttlockio.
