### ISSUE TITLE
Cannot connect to mqtt

### ISSUE THREAD

**Issue by tanushshukla** [tonyldo/tonyldo-hassio-addons#21]
Hello,

So I tried to follow the readme/tutorial and I think there is some issue connecting to MQTT.
 
First of all, I have done the python/create user part. I can get my lock/gateway via python.

But when I connect via the hassio addon, I get "OSError: [Errno 99] Address not available"

`
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun ttlock2mqtt (no readiness notification)
s6-rc: info: service legacy-services successfully started
[20:39:39] ERROR: Got unexpected response from the API: Service not enabled
[20:39:40] INFO: Run application...
2022-10-16 20:39:40 - [DEBUG] TTLOCK2MQTT: Options: {client_Id}, {client_token}, localhost, 1883, None, None, DEBUG, 60, 300, 200
2022-10-16 20:39:40 - [DEBUG] TTLOCK2MQTT: Starting main loop...
2022-10-16 20:39:40 - [DEBUG] TTLOCK2MQTT: Starting new HTTPS connection (1): euapi.ttlock.com:443
2022-10-16 20:39:40 - [DEBUG] TTLOCK2MQTT: https://euapi.ttlock.com:443 "GET /v3/gateway/list?clientId={client_Id}&accessToken={client_token}&pageNo=1&pageSize=20&date=1665949180305 HTTP/1.1" 200 251
2022-10-16 20:39:40 - [INFO] TTLOCK2MQTT: Client GATEWAY-466660-1665949180 TTlock Mqtt Created
2022-10-16 20:39:40 - [INFO] TTLOCK2MQTT: Client GATEWAY-466660-1665949180 TTlock Mqtt on client_loop
2022-10-16 20:39:40 - [DEBUG] TTLOCK2MQTT: Client GATEWAY-466660-1665949180 try connection at localhost:1883
2022-10-16 20:39:40 - [ERROR] TTLOCK2MQTT: Client GATEWAY-466660-1665949180 Loop Thread Error 
Traceback (most recent call last):
  File "/usr/bin/ttlock_adapter.py", line 269, in client_loop
    ttlock2MqttClient.mqttConnection()
  File "/usr/bin/ttlock_adapter.py", line 42, in mqttConnection
    self.connect(self.broker_host, self.broker_port, self.keepalive_mqtt)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Address not available
2022-10-16 20:39:40 - [DEBUG] TTLOCK2MQTT: Client GATEWAY-466660-1665949180 return future

`

Can you tell me what can be the error? I feel like the error is "localhost".
I am running home assistant supervised. I feel like "localhost" will get the docker container IP. Also, instead of MQTT user and password, it is logging "None, None" which can be the issue maybe?

I have other devices via tasmota so I am pretty sure my mqtt configuration is fine. Don't know if it matters but I am not using mosquito. I am using EMQX.

Please help me here.

**Comment by tanushshukla** [comment]
So an update here, 

I finally got everything working using TTlock2MQTT


My issue was I was using EMQX for MQTT rather than Mosquitto.

Even though that should not cause any issues but it does. For some reason, it only works with mosquito.


Its up to you now to treat that as a bug or not.

**Comment by tonyldo** [comment]
Hello my friend, Sorry to not answer yet...
Yeah, this is a connection problem... Maybe some issue between Paho mqtt client package and MQEX server. I Will address this...

**Comment by tonyldo** [comment]
Hello my friend, Sorry to not answer yet...
Yeah, this is a connection problem... Maybe some issue between Paho mqtt client package and EMQX server. I Will address this...

**Comment by tonyldo** [comment]
Here, can you confirm that your EMQX server has MQTT 5.0 version!?

This version was not suportted by Paho client, from EMQX docs:

Paho Python MQTT 5.0 support

Currently, Paho Python is still adapting to MQTT 5.0 and has not yet been fully supported it.

https://www.emqx.io/docs/en/v4.4/development/python.html#paho-python-mqtt-5-0-support

**Comment by tanushshukla** [comment]
No worries mate.

You are right. It is indeed v5, v5.0.10 to be precise.


I was using HA add-on for EMQX.
