### ISSUE TITLE
The addon is not working anymore

### ISSUE THREAD

**Issue by Zylazy** [tonyldo/tonyldo-hassio-addons#25]
Since yesterday it is not working. I have restarted the addon and also HA, but no luck.
The state of the lock is not updating.
This is what I can find in the logs:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun ttlock2mqtt (no readiness notification)
s6-rc: info: service legacy-services successfully started
[22:28:31] ERROR: Got unexpected response from the API: Service not enabled
[22:28:32] INFO: Run application...
2024-02-06 22:28:33 - [DEBUG] TTLOCK2MQTT: Options: XXXX, XXXX, localhost, 1883, None, None, DEBUG, 10, 300, 200
2024-02-06 22:28:33 - [DEBUG] TTLOCK2MQTT: Starting main loop...
2024-02-06 22:28:33 - [DEBUG] TTLOCK2MQTT: Starting new HTTPS connection (1): euapi.ttlock.com:443
2024-02-06 22:28:33 - [DEBUG] TTLOCK2MQTT: https://euapi.ttlock.com:443 "GET /v3/gateway/list?clientId=XXXX&accessToken=XXXX&pageNo=1&pageSize=20&date=1707254913089 HTTP/1.1" 200 233
2024-02-06 22:28:33 - [INFO] TTLOCK2MQTT: Client GATEWAY-XXXX-XXXX TTlock Mqtt Created
2024-02-06 22:28:33 - [INFO] TTLOCK2MQTT: Client GATEWAY-XXXX-XXXX TTlock Mqtt on client_loop
2024-02-06 22:28:33 - [DEBUG] TTLOCK2MQTT: Client GATEWAY-XXXX-XXXX try connection at localhost:1883
2024-02-06 22:28:33 - [ERROR] TTLOCK2MQTT: Client GATEWAY-XXXX-XXXX Loop Thread Error 
Traceback (most recent call last):
  File "/usr/bin/ttlock_adapter.py", line 269, in client_loop
    ttlock2MqttClient.mqttConnection()
  File "/usr/bin/ttlock_adapter.py", line 42, in mqttConnection
    self.connect(self.broker_host, self.broker_port, self.keepalive_mqtt)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Address not available
2024-02-06 22:28:33 - [DEBUG] TTLOCK2MQTT: Client GATEWAY-XXXX-XXXX return future

The mqtt is working, it is used also by tasmota, without any issue. The ttlock can be managed by the Android app via BT and also via the gateway remotely.

**Comment by Zylazy** [comment]
Today I have updated the OS to 11.5, and after that the problem was solved. I don't know if it was the real solution, or not, But now it is working again.
